# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subinf.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csubinf.proto\x12\tinference\"\xac\x01\n\nSensorData\x12\x16\n\x0e\x61\x63\x63\x65leration_x\x18\x01 \x01(\x02\x12\x16\n\x0e\x61\x63\x63\x65leration_y\x18\x02 \x01(\x02\x12\x16\n\x0e\x61\x63\x63\x65leration_z\x18\x03 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x01(\x02\x12\x13\n\x0b\x64\x65vice_name\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"!\n\x0fInferenceResult\x12\x0e\n\x06result\x18\x01 \x01(\t2V\n\x10InferenceService\x12\x42\n\x0bProcessData\x12\x15.inference.SensorData\x1a\x1a.inference.InferenceResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subinf_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORDATA']._serialized_start=28
  _globals['_SENSORDATA']._serialized_end=200
  _globals['_INFERENCERESULT']._serialized_start=202
  _globals['_INFERENCERESULT']._serialized_end=235
  _globals['_INFERENCESERVICE']._serialized_start=237
  _globals['_INFERENCESERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
